[project]
name = "prefect-testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "prefect>=3.4.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
